### ISSUE TITLE
stream doesn't respect projections

### ISSUE THREAD

**Issue by mvanwaaijen** [kofrasa/mingo-stream#1]
Hi,

When using the stream, it looks like projections aren't used? It doesn't matter if I specify a projection in the Query or not, I always get the entire object returned. Also when looking at the code I see that you do a query.test() on the chunk and then return the entire chunk...

Is it possible to use projections in the stream also?

Thanks,

**Comment by kofrasa** [comment]
Hi @mvanwaaijen, thanks for reporting an issue.

It will be great if you could attach some code samples to show how this can be reproduced.

This library is for streaming the JSON input directly and filtering on it. Projections should be supported but there is a small bug in the code where the projection is not passed to the cursor.

https://github.com/kofrasa/mingo-stream/blob/master/mingo-stream.js#L37

**Comment by mvanwaaijen** [comment]
hi @kofrasa ,

Here is some example code:

test.json:
`[
    {"_id": 1, "field": "abc", "logLevel": "WARNING" },
    {"_id": 2, "field": "def", "logLevel": "ERROR" },
    {"_id": 3, "field": "ghi", "logLevel": "INFO" },
    {"_id": 4, "field": "jkl", "logLevel": "ERROR" }
]`

example.js:
`const Mingo = require('mingo');
const ms = require('mingo-stream');
const fs = require('fs');
const jsonstream = require('jsonstream');

let query = new Mingo.Query({ "logLevel": { $in: ["ERROR"] } }, { "_id": 0, field: 1 });

const qs = ms(query);
qs.on('data', function (data) {
    console.log(data);
})

const stream = fs.createReadStream('../input-data/test.json');
stream.pipe(jsonstream.parse('*')).pipe(qs)`

running this should return 
`
{ field: 'def' }
{ field: 'jkl' }
`

but it actually returns all fields:
`
{ _id: 2, field: 'def', logLevel: 'ERROR' }
{ _id: 4, field: 'jkl', logLevel: 'ERROR' }
`
